//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Emu23.rc
//
#define IDS_MEMFLAGS                    1
#define IDC_MYICON                      2
#define IDS_APPWINDOW                   2
#define IDB_SET                         3
#define IDS_STTHDR                      3
#define IDB_SINGLE                      4
#define IDS_MEMHDR                      4
#define IDS_START                       5
#define IDB_REFRESH                     6
#define IDS_LENGTH                      6
#define IDS_BEGINDATA                   7
#define IDS_BEGINREG                    8
#define IDS_PCREG                       9
#define IDS_AREG                        10
#define IDS_XREG                        11
#define IDS_YREG                        12
#define IDS_FLAGREG                     13
#define IDS_SPREG                       14
#define IDS_HALTREG                     15
#define IDS_TICKREG                     16
#define IDS_ENDREG                      17
#define IDS_ENDDATA                     18
#define IDS_MACMEMFLAGS                 19
#define ID_FILE_EXIT                    101
#define IDD_EMU23_DIALOG                102
#define ID_HELP_CONTENTS                102
#define IDR_ACCELERATOR1                102
#define IDC_SPIN1                       102
#define IDS_APP_TITLE                   103
#define IDD_ABOUTBOX                    103
#define ID_HELP_SEARCH                  103
#define APP_ICON_ID                     103
#define ID_WINDOW_MEMORY                104
#define APP_MEM_ID                      104
#define IDD_STATUS                      104
#define IDM_EXIT                        105
#define ID_WINDOW_CPU                   105
#define IDC_SPIN3                       105
#define ID_WINDOW_CLOSEALL              106
#define IDI_OOPS                        106
#define IDI_EMU23                       107
#define ID_FILE_NEW                     107
#define IDC_SPIN5                       107
#define IDI_SMALL                       108
#define ID_FILE_OPEN                    108
#define IDC_EMU23                       109
#define ID_FILE_SAVE                    109
#define IDC_SPIN7                       109
#define ID_FILE_SAVEAS                  110
#define IDC_SPIN2                       110
#define ID_FILE_CLOSE                   111
#define IDC_SPIN4                       111
#define IDC_SPIN6                       112
#define IDC_SPIN8                       113
#define IDM_ABOUT                       114
#define IDR_MAINFRAME                   128
#define IDC_STARTADD                    1000
#define IDC_EDITMEM                     1000
#define IDC_HEXVAL                      1000
#define IDC_LOCATION                    1001
#define IDC_SIGNC                       1001
#define IDC_OVRC                        1002
#define IDC_ERROR                       1003
#define IDC_UNUSEDC                     1003
#define IDC_ZEROMEM                     1004
#define IDC_BREAKC                      1004
#define IDC_ENDADD                      1005
#define IDC_DECC                        1005
#define IDC_INTC                        1006
#define IDC_ZEROC                       1007
#define IDC_CARRYC                      1008
#define IDC_EDITSP                      1009
#define IDC_EDITA                       1010
#define IDC_EDITX                       1011
#define IDC_EDITY                       1012
#define IDC_EDITIP                      1013
#define IDC_HALTX                       1014
#define IDB_HALT                        1016
#define IDB_GO                          1017
#define IDD_OPENDLG                     1536
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        129
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           110
#endif
#endif
